### ISSUE TITLE
About the License of this Repository

### ISSUE THREAD

**Issue by MasatoKubotera** [RomdhoniZidane20/ichiro_dxl_board#1]
Hello. I am Masato Kubotera from CIT Brains, participating in the RoboCup Humanoid League from Japan.

I have a question about "https://github.com/RomdhoniZidane20/MARIN_CORE/tree/main/electronics" published in this repository.

The Eagle library used for the brd and sch files in this folder is very similar to the one I made.

I realized that my work was released under the license and that it may have been used without complying with that license.

If you are using my work, I would appreciate it if you could comply with the license.

If I'm wrong, please close the issue.

**Comment by RomdhoniZidane20** [comment]
Hello Masato, that's right about a number of the library that i used it's from SUSTAINA-OP
i will add the attribution from your repository to my repository as soon as possible
i'm sorry for the inconvenience

**Comment by RomdhoniZidane20** [comment]
i just updated the repository with license attribution

you can check this link below https://github.com/RomdhoniZidane20/MARIN_CORE/tree/main/electronics 

you can reply this message if there any issue with the license complying
